# Generated by Django 4.1 on 2022-08-31 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_tag_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='comment',
        ),
    ]
